[package]
name = "mnist_dataset"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = ["dataset"], optional = true }

ndarray = { version = "0.16.1", optional = true }

[features]
default = []
ndarray = ["dep:ndarray"]
burn = ["dep:burn"]
